const express = require('express');
const session = require('express-session');
const mysql = require('mysql2');
const crypto = require('crypto'); // Bawaan nodejs buat bikin random key
const app = express();
const port = 3000;

// ==========================================
// 1. KONEKSI DATABASE
// ==========================================
const db = mysql.createConnection({
    host: 'localhost', user: 'root', password: '', database: 'nct_archive'
});

db.connect((err) => {
    if (err) console.error('❌ DB Error:', err);
    else console.log('✅ Connected to NCTverse Database!');
});

// ==========================================
// 2. CONFIG SERVER & SESSION
// ==========================================
app.set('view engine', 'ejs');
app.use(express.static('public'));
app.use(express.urlencoded({ extended: true }));

app.use(session({
    secret: 'nct-super-secret-key',
    resave: false, saveUninitialized: true, cookie: { maxAge: 24 * 60 * 60 * 1000 }
}));

// ==========================================
// 3. MIDDLEWARE SATPAM (SECURITY)
// ==========================================
const cekAdmin = (req, res, next) => {
    if (req.session.role === 'admin') next();
    else res.redirect('/login');
};

const cekUser = (req, res, next) => {
    if (req.session.role === 'user') next();
    else res.redirect('/developer/login');
};

const cekApiKey = (req, res, next) => {
    const key = req.query.key; 
    if (!key) return res.status(401).send("API Key diperlukan!");

    db.query('SELECT * FROM api_users WHERE api_key = ?', [key], (err, results) => {
        if (err || results.length === 0) return res.status(403).send("API Key tidak valid.");
        if (results[0].status === 'inactive') return res.status(403).send("API Key NON-AKTIF (Hubungi Admin).");
        next(); 
    });
};

// ==========================================
// 4. ROUTE PUBLIC & DEVELOPER (USER)
// ==========================================
app.get('/', (req, res) => res.render('index'));

// Register & Login Developer
app.get('/developer/register', (req, res) => res.render('user/register'));
app.post('/developer/register', (req, res) => {
    const { email, password, nama_lengkap } = req.body;
    db.query('INSERT INTO api_users (email, password, nama_lengkap) VALUES (?, ?, ?)', 
    [email, password, nama_lengkap], (err) => {
        if(err) return res.send("Email error/sudah terdaftar.");
        res.redirect('/developer/login');
    });
});
app.get('/developer/login', (req, res) => res.render('user/login'));
app.post('/developer/login', (req, res) => {
    const { email, password } = req.body;
    db.query('SELECT * FROM api_users WHERE email = ? AND password = ?', [email, password], (err, results) => {
        if(results.length > 0) {
            req.session.role = 'user';
            req.session.userId = results[0].id;
            req.session.userName = results[0].nama_lengkap;
            res.redirect('/developer/dashboard');
        } else {
            res.send("Login Gagal");
        }
    });
});

// Dashboard Developer
app.get('/developer/dashboard', cekUser, (req, res) => {
    db.query('SELECT * FROM api_users WHERE id = ?', [req.session.userId], (err, result) => {
        res.render('user/dashboard', { user: result[0] });
    });
});
app.post('/developer/generate-key', cekUser, (req, res) => {
    const newKey = 'nct_' + crypto.randomBytes(16).toString('hex');
    db.query('UPDATE api_users SET api_key = ? WHERE id = ?', [newKey, req.session.userId], (err) => {
        res.redirect('/developer/dashboard');
    });
});
app.get('/developer/logout', (req, res) => req.session.destroy(() => res.redirect('/developer/login')));

// ==========================================
// 5. API ENDPOINTS (PROVIDER)
// ==========================================
app.get('/api/v1/members', cekApiKey, (req, res) => {
    db.query('SELECT * FROM members', (err, results) => {
        res.json({ status: "success", total_data: results.length, data: results });
    });
});
app.get('/api/v1/member/:id', cekApiKey, (req, res) => {
    db.query('SELECT * FROM members WHERE id = ?', [req.params.id], (err, results) => {
        if(results.length === 0) return res.status(404).json({status: "fail"});
        res.json({ status: "success", data: results[0] });
    });
});
app.get('/api/v1/download/member/:id', cekApiKey, (req, res) => {
    const id = req.params.id;
    db.query('SELECT * FROM members WHERE id = ?', [id], (err, results) => {
        if (err || results.length === 0) return res.send("Data not found");
        const m = results[0];
        const content = `NCT MEMBER REPORT\nID: ${m.id}\nNama: ${m.nama_panggung}\nPosisi: ${m.posisi}\nAsal: ${m.asal_negara}\n\nGenerated by NCT API Center`;
        res.setHeader('Content-disposition', `attachment; filename=${m.nama_panggung}.txt`);
        res.setHeader('Content-type', 'text/plain');
        res.send(content);
    });
});

// ==========================================
// 6. ROUTE ADMIN (BACKEND UTAMA)
// ==========================================
app.get('/login', (req, res) => req.session.role === 'admin' ? res.redirect('/admin') : res.render('login', {error: null}));
app.post('/login', (req, res) => {
    const { username, password } = req.body;
    db.query('SELECT * FROM admin WHERE username = ? AND password = ?', [username, password], (err, resDb) => {
        if(resDb.length > 0) {
            req.session.role = 'admin';
            res.redirect('/admin');
        } else {
            res.render('login', {error: "Login Gagal!"});
        }
    });
});

// --- ADMIN DASHBOARD ---
app.get('/admin', cekAdmin, (req, res) => {
    // Kita hapus hitung albums, ganti jadi hitung USERS
    const sqlCount = `SELECT 
        (SELECT COUNT(*) FROM units) as totalUnits, 
        (SELECT COUNT(*) FROM members) as totalMembers, 
        (SELECT COUNT(*) FROM api_users) as totalUsers`; 

    db.query(sqlCount, (err, results) => {
        res.render('admin/dashboard', {
            totalUnits: results[0].totalUnits,
            totalMembers: results[0].totalMembers,
            totalUsers: results[0].totalUsers // Data user dikirim ke view
        });
    });
});

// --- FITUR BARU: MANAJEMEN USER ---
// A. List User
app.get('/admin/users', cekAdmin, (req, res) => {
    db.query('SELECT * FROM api_users ORDER BY id DESC', (err, results) => {
        res.render('admin/users', { users: results });
    });
});
// B. Detail User
app.get('/admin/users/detail/:id', cekAdmin, (req, res) => {
    db.query('SELECT * FROM api_users WHERE id = ?', [req.params.id], (err, result) => {
        res.render('admin/user_detail', { user: result[0] });
    });
});
// C. Toggle Status
app.get('/admin/users/toggle/:id/:status', cekAdmin, (req, res) => {
    const newStatus = req.params.status === 'active' ? 'inactive' : 'active';
    db.query('UPDATE api_users SET status = ? WHERE id = ?', [newStatus, req.params.id], () => {
        res.redirect(`/admin/users/detail/${req.params.id}`);
    });
});

// --- CRUD Member & Unit ---
app.get('/admin/members', cekAdmin, (req, res) => db.query('SELECT * FROM members ORDER BY id DESC', (err, r) => res.render('admin/members', { members: r })));
app.get('/admin/members/add', cekAdmin, (req, res) => db.query('SELECT * FROM units', (err, r) => res.render('admin/member_form', { units: r })));
app.post('/admin/members/add', cekAdmin, (req, res) => {
    const { nama_panggung, nama_lengkap, tgl_lahir, asal_negara, posisi, biografi, foto } = req.body;
    db.query('INSERT INTO members (nama_panggung, nama_lengkap, tgl_lahir, asal_negara, posisi, biografi, foto) VALUES (?, ?, ?, ?, ?, ?, ?)', 
    [nama_panggung, nama_lengkap, tgl_lahir, asal_negara, posisi, biografi, foto], () => res.redirect('/admin/members'));
});
app.get('/admin/members/edit/:id', cekAdmin, (req, res) => { 
    db.query('SELECT * FROM members WHERE id=?',[req.params.id],(e,r)=> {
        db.query('SELECT * FROM units', (err, u) => {
             res.render('admin/member_edit',{member:r[0], units:u, currentUnitIds:[]})
        })
    }); 
}); 
app.post('/admin/members/update/:id', cekAdmin, (req, res) => {
    const { nama_panggung, nama_lengkap, tgl_lahir, asal_negara, posisi, biografi, foto } = req.body;
    db.query('UPDATE members SET nama_panggung=?, nama_lengkap=?, tgl_lahir=?, asal_negara=?, posisi=?, biografi=?, foto=? WHERE id=?', 
    [nama_panggung, nama_lengkap, tgl_lahir, asal_negara, posisi, biografi, foto, req.params.id], () => res.redirect('/admin/members'));
});
app.get('/admin/members/delete/:id', cekAdmin, (req, res) => db.query('DELETE FROM members WHERE id=?',[req.params.id],()=>res.redirect('/admin/members')));

app.get('/admin/units', cekAdmin, (req, res) => db.query('SELECT * FROM units', (e,r)=>res.render('admin/units',{units:r})));
app.get('/admin/units/add', cekAdmin, (req, res) => res.render('admin/unit_form'));
app.post('/admin/units/add', cekAdmin, (req, res) => {
    const { nama_unit, deskripsi, logo } = req.body;
    db.query('INSERT INTO units (nama_unit, deskripsi, logo) VALUES (?, ?, ?)', [nama_unit, deskripsi, logo], () => res.redirect('/admin/units'));
});
app.get('/admin/units/delete/:id', cekAdmin, (req, res) => db.query('DELETE FROM units WHERE id = ?', [req.params.id], () => res.redirect('/admin/units')));

app.get('/logout', (req, res) => req.session.destroy(() => res.redirect('/login')));

app.listen(port, () => console.log(`🚀 NCT API Center running at http://localhost:${port}`));