const express = require('express');
const mysql = require('mysql2');
const app = express();
const port = 3000;

// 1. KONEKSI DATABASE

const db = mysql.createConnection({
    host: 'localhost',
    user: 'root',
    password: '',
    database: 'nct_archive'
});

db.connect((err) => {
    if (err) console.error('❌ DB Error:', err);
    else console.log('✅ Connected to NCTverse Database!');
});

app.set('view engine', 'ejs');
app.use(express.static('public'));

app.use(express.urlencoded({ extended: true }));
// 2. RUTE HALAMAN WEB (VIEW)
// --- HOME ---
app.get('/', (req, res) => {
    db.query('SELECT * FROM units', (err, results) => {
        if (err) throw err;
        res.render('index', { units: results });
    });
});

// --- DETAIL UNIT ---
app.get('/unit/:id', (req, res) => {
    const unitId = req.params.id;
    
    // Ambil Data Unit
    db.query('SELECT * FROM units WHERE id = ?', [unitId], (err, resultUnit) => {
        if (err) throw err;
        if (resultUnit.length === 0) return res.send('Unit tidak ditemukan');

        // Ambil Member di unit ini
        const sqlMembers = `
            SELECT m.* FROM members m 
            JOIN member_unit mu ON m.id = mu.member_id 
            WHERE mu.unit_id = ?`;
        
        db.query(sqlMembers, [unitId], (err, resultMembers) => {
            if (err) throw err;

            // Ambil Album unit ini
            db.query('SELECT * FROM albums WHERE unit_id = ?', [unitId], (err, resultAlbums) => {
                if (err) throw err;

                res.render('unit', {
                    unit: resultUnit[0],
                    members: resultMembers,
                    albums: resultAlbums
                });
            });
        });
    });
});

// --- DETAIL MEMBER ---
app.get('/member/:id', (req, res) => {
    const memberId = req.params.id;

    // Ambil Biodata Member
    db.query('SELECT * FROM members WHERE id = ?', [memberId], (err, resultMember) => {
        if (err) throw err;
        if (resultMember.length === 0) return res.send('Member tidak ditemukan');

        // Ambil Daftar Unit Member Tersebut
        const sqlUnits = `
            SELECT u.nama_unit FROM units u 
            JOIN member_unit mu ON u.id = mu.unit_id 
            WHERE mu.member_id = ?`;

        db.query(sqlUnits, [memberId], (err, resultUnits) => {
            if (err) throw err;

            res.render('member', {
                member: resultMember[0],
                units: resultUnits
            });
        });
    });
});

// 3. API ENDPOINTS (FITUR DOWNLOAD DATA)
// --- API DOWNLOAD REPORT MEMBER (.txt) ---
app.get('/api/member/:id', (req, res) => {
    const memberId = req.params.id;

    // Ambil data lagi untuk dijadikan teks
    db.query('SELECT * FROM members WHERE id = ?', [memberId], (err, memberData) => {
        if (err) throw err;
        if (memberData.length === 0) return res.send('Data not found');

        const m = memberData[0];

        // Format Laporan Teks
        const content = `
DATA REPORT: NCT ARCHIVE SYSTEM
------------------------------------------
ID Member   : ${m.id}
Nama Panggung: ${m.nama_panggung}
Nama Lengkap : ${m.nama_lengkap}
Asal        : ${m.asal_negara}
Posisi      : ${m.posisi}
------------------------------------------
BIOGRAFI:
${m.biografi || 'Tidak ada data biografi.'}
------------------------------------------
Generated by NCT Open Data Center
        `;

        // download file
        res.setHeader('Content-disposition', `attachment; filename=data_${m.nama_panggung}.txt`);
        res.set('Content-Type', 'text/plain');
        res.send(content);
    });
});

// API DOWNLOAD TRACKLIST ALBUM (.txt)
app.get('/api/album/:id', (req, res) => {
    const albumId = req.params.id;

    db.query('SELECT * FROM albums WHERE id = ?', [albumId], (err, albumData) => {
        if (err) throw err;
        if (albumData.length === 0) return res.send('Album not found');

        // Ambil lagu-lagu di album ini
        db.query('SELECT * FROM songs WHERE album_id = ?', [albumId], (err, songs) => {
            if (err) throw err;

            const a = albumData[0];
            
            // Susun list lagu jadi teks
            let songListText = "";
            songs.forEach((song, index) => {
                songListText += `${index + 1}. ${song.judul_lagu}\n`;
            });

            const content = `
TRACKLIST REPORT: NCT ARCHIVE
------------------------------------------
Album  : ${a.judul}
Rilis  : ${a.tgl_rilis}
------------------------------------------
DAFTAR LAGU:
${songListText || 'Belum ada data lagu.'}
------------------------------------------
Generated by NCT Open Data Center
            `;

            res.setHeader('Content-disposition', `attachment; filename=tracklist_${a.judul}.txt`);
            res.set('Content-Type', 'text/plain');
            res.send(content);
        });
    });
});

// API DOWNLOAD DATA UNIT (.txt) 
app.get('/api/unit/:id', (req, res) => {
    const unitId = req.params.id;

    db.query('SELECT * FROM units WHERE id = ?', [unitId], (err, unitData) => {
        if (err) throw err;
        if (unitData.length === 0) return res.send('Unit not found');

        const u = unitData[0];

        const content = `
UNIT REPORT: NCT ARCHIVE
------------------------------------------
ID Unit     : ${u.id}
Nama Unit   : ${u.nama_unit}
------------------------------------------
DESKRIPSI:
${u.deskripsi}
------------------------------------------
Generated by NCT Open Data Center
        `;

        res.setHeader('Content-disposition', `attachment; filename=data_${u.nama_unit}.txt`);
        res.set('Content-Type', 'text/plain');
        res.send(content);
    });
});

//admin
app.get('/admin', (req, res) => {
    // Hitung jumlah data untuk dashboard
    const sqlCount = `
        SELECT 
            (SELECT COUNT(*) FROM units) as totalUnits,
            (SELECT COUNT(*) FROM members) as totalMembers,
            (SELECT COUNT(*) FROM albums) as totalAlbums
    `;

    db.query(sqlCount, (err, results) => {
        if (err) throw err;
        
        // Render file admin/dashboard.ejs
        res.render('admin/dashboard', {
            totalUnits: results[0].totalUnits,
            totalMembers: results[0].totalMembers,
            totalAlbums: results[0].totalAlbums
        });
    });
});

// --- 1. TAMPILKAN HALAMAN FORMULIR ---
app.get('/admin/members/add', (req, res) => {
    // Kita butuh data units supaya bisa muncul di Checkbox
    db.query('SELECT * FROM units', (err, results) => {
        if (err) throw err;
        res.render('admin/member_form', { units: results });
    });
});
//rute tambah tabel members
app.get('/admin/members', (req, res) => {
    const sql = 'SELECT * FROM members ORDER BY id DESC'; // Urutkan dari yang terbaru
    
    db.query(sql, (err, results) => {
        if (err) throw err;
        
        // Kirim data members ke halaman tabel
        res.render('admin/members', { members: results });
    });
});

// --- 2. PROSES SIMPAN DATA (POST) ---
app.post('/admin/members/add', (req, res) => {
    const { nama_panggung, nama_lengkap, tgl_lahir, asal_negara, posisi, biografi, foto, units } = req.body;

    // A. Simpan ke tabel 'members' dulu
    const sqlMember = `INSERT INTO members (nama_panggung, nama_lengkap, tgl_lahir, asal_negara, posisi, biografi, foto) VALUES (?, ?, ?, ?, ?, ?, ?)`;
    
    db.query(sqlMember, [nama_panggung, nama_lengkap, tgl_lahir, asal_negara, posisi, biografi, foto], (err, result) => {
        if (err) {
            console.error(err);
            return res.send('Gagal menyimpan member.');
        }

        // B. Ambil ID member yang barusan dibuat
        const newMemberId = result.insertId;
        
        // C. Simpan Relasi Unit (Jika ada unit yg dipilih)
        if (units) {
            // Cek apakah units itu array (banyak) atau string (satu)
            // Kalau cuma pilih 1, dia jadi string. Kalau banyak jadi array.
            const unitArray = Array.isArray(units) ? units : [units];

            // Siapkan data untuk insert massal
            const values = unitArray.map(unitId => [newMemberId, unitId]);
            
            const sqlRelasi = 'INSERT INTO member_unit (member_id, unit_id) VALUES ?';
            db.query(sqlRelasi, [values], (err) => {
                if (err) console.error(err);
                // Selesai! Kembali ke dashboard
                res.redirect('/admin'); 
            });
        } else {
            res.redirect('/admin');
        }
    });
});
app.get('/admin/members/delete/:id', (req, res) => {
    const memberId = req.params.id;

    // 1. Hapus dulu relasi unitnya (Biar database gak bingung)
    db.query('DELETE FROM member_unit WHERE member_id = ?', [memberId], (err) => {
        if (err) throw err;

        // 2. Baru hapus membernya
        db.query('DELETE FROM members WHERE id = ?', [memberId], (err) => {
            if (err) throw err;
            
            // Balik ke tabel list
            res.redirect('/admin/members');
        });
    });
});

// ==========================================
// FITUR EDIT MEMBER (UPDATE)
// ==========================================

// 1. TAMPILKAN FORM EDIT (GET)
app.get('/admin/members/edit/:id', (req, res) => {
    const memberId = req.params.id;

    // Query 1: Ambil data member
    db.query('SELECT * FROM members WHERE id = ?', [memberId], (err, memberResult) => {
        if (err) throw err;
        const member = memberResult[0];

        // Query 2: Ambil semua unit (buat pilihan checkbox)
        db.query('SELECT * FROM units', (err, unitsResult) => {
            if (err) throw err;

            // Query 3: Ambil ID unit yang SUDAH dimiliki member ini (biar checkbox tercentang)
            db.query('SELECT unit_id FROM member_unit WHERE member_id = ?', [memberId], (err, memberUnits) => {
                if (err) throw err;

                // Ubah format [{unit_id: 1}, {unit_id: 2}] jadi array biasa [1, 2]
                // Supaya gampang dicek di EJS
                const currentUnitIds = memberUnits.map(item => item.unit_id);

                // Kirim semua ke member_edit.ejs
                res.render('admin/member_edit', {
                    member: member,
                    units: unitsResult,
                    currentUnitIds: currentUnitIds
                });
            });
        });
    });
});

// 2. PROSES SIMPAN PERUBAHAN (POST)
app.post('/admin/members/update/:id', (req, res) => {
    const memberId = req.params.id;
    const { nama_panggung, nama_lengkap, tgl_lahir, asal_negara, posisi, biografi, foto, units } = req.body;

    // A. Update tabel members
    const sqlMember = `UPDATE members SET nama_panggung=?, nama_lengkap=?, tgl_lahir=?, asal_negara=?, posisi=?, biografi=?, foto=? WHERE id=?`;

    db.query(sqlMember, [nama_panggung, nama_lengkap, tgl_lahir, asal_negara, posisi, biografi, foto, memberId], (err) => {
        if (err) throw err;

        // B. Update Unit (Cara paling gampang: Hapus semua yg lama, Insert yg baru)
        // 1. Hapus relasi lama
        db.query('DELETE FROM member_unit WHERE member_id = ?', [memberId], (err) => {
            if (err) throw err;

            // 2. Masukkan relasi baru (Kalau ada yang dicentang)
            if (units) {
                const unitArray = Array.isArray(units) ? units : [units];
                const values = unitArray.map(uId => [memberId, uId]);

                db.query('INSERT INTO member_unit (member_id, unit_id) VALUES ?', [values], (err) => {
                    if (err) throw err;
                    res.redirect('/admin/members'); // Selesai
                });
            } else {
                // Kalau semua centang dihilangkan (dia gak punya unit)
                res.redirect('/admin/members');
            }
        });
    });
});

app.listen(port, () => {
    console.log(`🚀 Server berjalan di http://localhost:${port}`);
});